title: cd-beginner-scratch-sushi-scratch2
hero_image: images/banner.png
description: cd-beginner-scratch-sushi-scratch2 description
version: 4
listed: false
copyedit: false
last_tested: "2018-12-13"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
